"""Channel config and idea-generation routes.

Extracted from ``_legacy.py``.

MONKEYPATCH NOTE: Tests patch ``video_agent.web.routes._legacy.generate_ideas``
and ``video_agent.web.routes._legacy.load_published_videos`` via
``monkeypatch.setattr(legacy_routes, "generate_ideas", ...)``.  To preserve
this, the route handlers that call those functions perform a LATE import of
``_legacy`` inside the function body and call through that module's namespace,
so the monkeypatch remains effective.
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException

from video_agent.contracts import repo_root
from video_agent.orchestrator.browser_client import BrowserClient, BrowserClientError
from video_agent.orchestrator.stages import _idea_keywords

from video_agent.web.routes._common import (
    GenerateIdeasRequest,
    IdeaFromTitleRequest,
    ScoreIdeasRequest,
    _filter_keyword_result_for_ui,
    _handle_browser_client_error,
    _safe_channel_id,
    flatten_keyword_result_for_ui,
    get_browser_client,
    get_inputs_root,
    get_jobs_root,
    keyword_result_summary,
    keyword_score_payload,
)

router = APIRouter()


@router.get("/channels")
def list_channels() -> dict:
    """List available channel configs."""
    configs_dir = repo_root() / "configs"
    channels = []
    if configs_dir.exists():
        for p in sorted(configs_dir.iterdir()):
            if p.is_dir() and (p / "channel.yaml").exists():
                channels.append(p.name)
    return {"channels": channels}


@router.get("/channels/{channel_id}/ideas")
def list_saved_ideas(
    channel_id: str,
    inputs_root: Path = Depends(get_inputs_root),
) -> dict:
    """List saved idea JSON files for a channel (most recent first).

    Scans both inputs/ideas/{channel_id}/ (new generated ideas) and
    inputs/*.json root files (legacy batch ideas), returning all that
    look like valid idea objects (have at least a 'topic' field).
    """
    _safe_channel_id(channel_id)
    _IDEA_FIELDS = {"topic", "angle", "title_seed", "key_points"}
    ideas: list[dict] = []
    paths: list[str] = []

    # ideas/{channel_id}/ subdirectory (generated by idea_generator).
    # Root inputs/*.json fallback removed — it leaked ideas from other channels.
    ideas_dir = inputs_root / "ideas" / channel_id
    subdir_files: list[Path] = []
    if ideas_dir.exists():
        subdir_files = sorted(ideas_dir.glob("*.json"), key=lambda f: f.stat().st_mtime, reverse=True)

    for f in subdir_files:
        if len(ideas) >= 50:
            break
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
            if not isinstance(data, dict) or not (_IDEA_FIELDS & data.keys()):
                continue
            # Belt-and-braces: drop entries tagged with a different channel_id.
            if data.get("channel_id") and data.get("channel_id") != channel_id:
                continue
            ideas.append(data)
            paths.append(f"ideas/{channel_id}/{f.name}")
        except Exception:
            pass
    return {"channel_id": channel_id, "ideas": ideas, "paths": paths}


@router.post("/channels/{channel_id}/ideas/score")
async def post_score_ideas(
    channel_id: str,
    req: ScoreIdeasRequest,
    client: BrowserClient = Depends(get_browser_client),
) -> dict:
    """Estimate keyword quality for a list of ideas using local channel rules."""
    _safe_channel_id(channel_id)
    from video_agent.utils.json_io import read_yaml as _read_yaml
    channel_path = repo_root() / "configs" / channel_id / "channel.yaml"
    if not channel_path.exists():
        raise HTTPException(status_code=404, detail=f"No config for channel: {channel_id}")
    channel_config = _read_yaml(channel_path)
    # Collect all keywords from all ideas in one flat list, track ranges
    all_keywords: list[str] = []
    ranges: list[tuple[int, int]] = []
    for idea in req.ideas:
        kws = _idea_keywords(idea)
        ranges.append((len(all_keywords), len(all_keywords) + len(kws)))
        all_keywords.extend(kws)

    from video_agent.orchestrator.idea_generator import (
        enrich_keyword_item,
        merge_keyword_channel_config,
    )

    scoring_cfg = merge_keyword_channel_config(channel_config)
    all_scores = [
        enrich_keyword_item({"keyword": keyword, "score": None}, scoring_cfg)
        for keyword in all_keywords
    ]

    results = []
    for i, idea in enumerate(req.ideas):
        start, end = ranges[i]
        idea_scores = all_scores[start:end]
        valid = [s for s in idea_scores if isinstance(s.get("score"), (int, float))]
        best = int(max(s["score"] for s in valid)) if valid else None
        results.append({
            "topic": idea.get("topic", ""),
            "title_seed": idea.get("title_seed", ""),
            "keywords": all_keywords[start:end],
            "scores": idea_scores,
            "best_score": best,
            "competition": None,
            "related": [],
            "error": None,
        })

    return {"results": results, "error": None}


@router.get("/channels/{channel_id}/sync-videos")
async def get_sync_channel_videos(
    channel_id: str,
) -> dict:
    """Fetch published videos from YouTube RSS and cache to published_videos.json."""
    _safe_channel_id(channel_id)
    channel_path = repo_root() / "configs" / channel_id / "channel.yaml"
    if not channel_path.exists():
        raise HTTPException(status_code=404, detail=f"No config for channel: {channel_id}")
    from video_agent.utils.json_io import read_yaml as _read_yaml
    from video_agent.orchestrator.idea_generator import sync_published_videos
    channel_config = _read_yaml(channel_path)
    try:
        videos = sync_published_videos(channel_config, repo_root() / "configs")
    except ValueError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc
    return {"channel_id": channel_id, "count": len(videos), "videos": videos}


@router.delete("/channels/{channel_id}/ideas")
async def delete_saved_ideas(
    channel_id: str,
    inputs_root: Path = Depends(get_inputs_root),
) -> dict:
    """Delete every saved-idea JSON under ``inputs/ideas/<channel_id>/``.

    Returns ``{deleted: int}`` with the count of files removed. Files
    outside the channel folder are never touched. The directory itself
    is left in place (idempotent for the UI's load-saved flow).
    """
    _safe_channel_id(channel_id)
    ideas_dir = (inputs_root / "ideas" / channel_id).resolve()
    safe_root = (inputs_root / "ideas").resolve()
    try:
        ideas_dir.relative_to(safe_root)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=f"Invalid channel_id: {channel_id!r}") from exc
    if not ideas_dir.exists():
        return {"channel_id": channel_id, "deleted": 0}
    deleted = 0
    for p in ideas_dir.iterdir():
        if p.is_file() and p.suffix.lower() == ".json":
            try:
                p.unlink()
                deleted += 1
            except OSError:
                continue
    return {"channel_id": channel_id, "deleted": deleted}


@router.get("/channels/{channel_id}/videos")
async def get_channel_videos(channel_id: str) -> dict:
    """Return the cached YouTube channel videos plus the channel's
    ``youtube_channel_id`` so the dashboard can render direct links.

    Reads ``configs/<channel_id>/published_videos.json`` written by
    ``/channels/{id}/sync-videos``. Returns ``{count, videos, channel_url,
    synced_at}``; ``videos: []`` when the cache is missing instead of a
    404 so the UI can still render an empty list with a "Sync" CTA.
    """
    _safe_channel_id(channel_id)
    channel_path = repo_root() / "configs" / channel_id / "channel.yaml"
    if not channel_path.exists():
        raise HTTPException(status_code=404, detail=f"No config for channel: {channel_id}")
    from video_agent.utils.json_io import read_yaml as _read_yaml

    channel_config = _read_yaml(channel_path)
    cache_path = repo_root() / "configs" / channel_id / "published_videos.json"
    videos: list[dict] = []
    synced_at: str | None = None
    if cache_path.exists():
        try:
            data = json.loads(cache_path.read_text(encoding="utf-8"))
            videos = data.get("videos") or []
            synced_at = data.get("synced_at")
        except Exception:
            videos = []
    yt_channel_id = (channel_config.get("channel") or {}).get("youtube_channel_id")
    channel_url = (
        f"https://www.youtube.com/channel/{yt_channel_id}" if yt_channel_id else None
    )
    return {
        "channel_id": channel_id,
        "youtube_channel_id": yt_channel_id,
        "channel_url": channel_url,
        "count": len(videos),
        "videos": videos,
        "synced_at": synced_at,
    }


@router.post("/channels/{channel_id}/ideas/generate", status_code=201)
async def post_generate_ideas(
    channel_id: str,
    req: GenerateIdeasRequest,
    inputs_root: Path = Depends(get_inputs_root),
    client: BrowserClient = Depends(get_browser_client),
) -> dict:
    """Generate ideas via ChatGPT from user seeds or local trend seeds.

    NOTE: ``generate_ideas`` and ``load_published_videos`` are resolved
    through the ``_legacy`` module at call time so that test monkeypatches
    on ``legacy_routes.generate_ideas`` / ``legacy_routes.load_published_videos``
    remain effective.
    """
    # Late import — keeps monkeypatch on _legacy working.
    import video_agent.web.routes._legacy as _legacy_mod

    _safe_channel_id(channel_id)
    channel_path = repo_root() / "configs" / channel_id / "channel.yaml"
    if not channel_path.exists():
        raise HTTPException(status_code=404, detail=f"No config for channel: {channel_id}")

    if not 1 <= req.count <= 50:
        raise HTTPException(status_code=422, detail="count must be between 1 and 50")

    # Load cached published videos first — feed their titles into the idea
    # prompt so ChatGPT avoids already-published angles, and reuse them below
    # for duplicate detection.
    from video_agent.orchestrator.idea_generator import (
        MAX_PUBLISHED_TITLES_IN_IDEA_PROMPT,
        normalize_keyword,
        save_ideas,
        find_duplicate,
    )
    from video_agent.utils.json_io import read_yaml as _read_yaml
    channel_config = _read_yaml(channel_path)
    published = _legacy_mod.load_published_videos(channel_config, repo_root() / "configs")
    published_titles = [v["title"] for v in published if v.get("title")]
    published_titles = published_titles[:MAX_PUBLISHED_TITLES_IN_IDEA_PROMPT]

    try:
        ideas, top_keywords, seed_source = await _legacy_mod.generate_ideas(
            channel_path=channel_path,
            chatgpt_fn=lambda msgs: client.run_session("chatgpt", msgs),
            seed_topics=req.seed_topics,
            count=req.count,
            with_metadata=True,
            published_titles=published_titles,
        )
    except BrowserClientError as exc:
        raise _handle_browser_client_error(exc) from exc
    except ValueError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    top_keywords_for_ui = _filter_keyword_result_for_ui(top_keywords, channel_config)
    keywords_for_ui = flatten_keyword_result_for_ui(top_keywords_for_ui)
    summary = keyword_result_summary(top_keywords_for_ui)
    kw_score_map = {
        normalize_keyword(kw["keyword"]): kw
        for kw in keywords_for_ui
        if isinstance(kw, dict) and kw.get("keyword")
    }
    ideas_with_scores = []
    duplicate_candidates: list[dict] = []
    used_fallback_keywords: set[str] = set()
    for idx, idea in enumerate(ideas):
        enriched = dict(idea)
        target_kw = idea.get("target_keyword", "")
        target_norm = normalize_keyword(target_kw)
        kw_data = kw_score_map.get(target_norm, {})
        match_source = "target_keyword"
        if not kw_data and idx < len(keywords_for_ui):
            fallback = keywords_for_ui[idx]
            if isinstance(fallback, dict) and fallback.get("keyword"):
                fallback_norm = normalize_keyword(fallback["keyword"])
                if fallback_norm not in used_fallback_keywords:
                    kw_data = fallback
                    match_source = "ordered_fallback"
        if kw_data:
            used_fallback_keywords.add(normalize_keyword(kw_data.get("keyword", "")))
            enriched.update(keyword_score_payload(kw_data, target_kw, summary, match_source))
        # Re-score the idea using its richer title_seed (multi-word, intent
        # verbs) instead of the bare seed keyword. The keyword-discovery
        # phase may score a 1-2 word term that lands in rejected_keywords
        # (intent_strength=25). The ChatGPT-fleshed idea
        # title carries the real intent signal — re-scoring against the
        # title reflects the actual quality the user judges in the UI.
        from video_agent.orchestrator.idea_generator import (
            score_intent_strength as _intent_fn,
            score_audience_fit as _aud_fn,
            score_content_fit as _content_fn,
            calculate_final_score as _final_fn,
            assign_bucket as _bucket_fn,
            detect_language_fit as _language_fn,
            merge_keyword_channel_config as _merge_cfg,
        )
        title_for_scoring = (
            enriched.get("title_seed") or enriched.get("topic") or target_kw
        )
        if title_for_scoring:
            cfg = _merge_cfg(_read_yaml(channel_path))
            new_intent = _intent_fn(title_for_scoring)
            new_audience = _aud_fn(title_for_scoring, cfg)
            new_content = _content_fn(title_for_scoring, cfg)
            # Re-check language at the title level — a ChatGPT title in the
            # wrong locale/language must be caught even if the seed keyword
            # scored as clean Spanish.
            new_language, language_notes = _language_fn(
                title_for_scoring, cfg["target_language"]
            )
            existing_notes = list(
                enriched.get("keyword_notes")
                or enriched.get("notes")
                or []
            )
            combined_notes = sorted(set(existing_notes + list(language_notes)))
            scoring = {
                "keyword": title_for_scoring,
                "keyword_source_score": enriched.get("keyword_source_score"),
                "audience_fit": max(enriched.get("audience_fit") or 0, new_audience),
                "intent_strength": max(enriched.get("intent_strength") or 0, new_intent),
                "content_fit": max(enriched.get("content_fit") or 0, new_content),
                "language_fit": new_language,
                "serp_opportunity": enriched.get("serp_opportunity") or 50,
                "notes": combined_notes,
                "rejection_reasons": [],
            }
            _final_fn(scoring)
            new_bucket = _bucket_fn(scoring)
            enriched["intent_strength"] = scoring["intent_strength"]
            enriched["audience_fit"] = scoring["audience_fit"]
            enriched["content_fit"] = scoring["content_fit"]
            enriched["language_fit"] = scoring["language_fit"]
            enriched["keyword_final_score"] = scoring["final_score"]
            enriched["bucket"] = new_bucket
            # Append language notes without overwriting existing keyword notes.
            enriched["keyword_notes"] = sorted(set(
                list(enriched.get("keyword_notes") or [])
                + list(scoring.get("notes") or [])
            ))
        # Duplicate check against published channel videos. Duplicates are
        # returned separately and NOT saved as normal ideas.
        dup = find_duplicate(enriched, published)
        if dup:
            enriched["is_duplicate"] = True
            enriched["duplicate_of"] = dup
            duplicate_candidates.append(enriched)
            continue
        enriched["is_duplicate"] = False
        enriched["duplicate_of"] = None
        ideas_with_scores.append(enriched)

    paths = save_ideas(ideas_with_scores, channel_id=channel_id, out_dir=inputs_root)
    rel_paths = [str(p.relative_to(inputs_root)) for p in paths]

    return {
        "channel_id": channel_id,
        "count": len(ideas_with_scores),
        "ideas": ideas_with_scores,
        "keyword_result": top_keywords_for_ui,
        "top_keywords": top_keywords_for_ui,
        "summary": summary,
        "seed_source": seed_source,
        "published_videos_checked": len(published),
        "saved": rel_paths,
        "duplicate_candidates": duplicate_candidates,
        "duplicate_count": len(duplicate_candidates),
    }


@router.post("/channels/{channel_id}/ideas/from-title", status_code=201)
async def post_idea_from_title(
    channel_id: str,
    req: IdeaFromTitleRequest,
    inputs_root: Path = Depends(get_inputs_root),
    jobs_root: Path = Depends(get_jobs_root),
    client: BrowserClient = Depends(get_browser_client),
) -> dict:
    """Expand a bare title into one enriched idea (Idea Generator card shape).

    No job is created — the idea is saved and returned so the UI can render it
    as a card; the video is created later via ``/jobs/from-idea``.
    """
    _safe_channel_id(channel_id)
    from video_agent.web.services.video_job_creator import create_idea_from_title

    return await create_idea_from_title(
        channel_id=channel_id,
        title_seed=req.title_seed,
        jobs_root=jobs_root,
        inputs_root=inputs_root,
        browser_client=client,
    )
