"""Module-level constants for idea generation (keyword config, markers, etc.)."""

from __future__ import annotations

__all__ = [
    "IDEAS_SUBDIR",
    "PUBLISHED_VIDEOS_FILE",
    "_TITLE_STOPWORDS",
    "_NICHE_KW_MAP",
    "_CATEGORY_KW_MAP",
    "_REQUIRED_FIELDS",
    "DEFAULT_CHANNEL_KEYWORD_CONFIG",
    "PORTUGUESE_MARKERS",
    "SPANISH_MARKERS",
    "ENGLISH_MARKERS",
    "FRENCH_MARKERS",
    "ITALIAN_MARKERS",
    "_AGE_CHANNEL_MARKERS",
    "INTENT_KEYWORDS",
    "UNSAFE_CLAIMS",
    "GENERIC_KEYWORDS",
    "HIGH_RISK_MEDICAL_TOPICS",
    "VALID_45PLUS_SENSITIVE_TOPICS",
    "MAX_PUBLISHED_TITLES_IN_IDEA_PROMPT",
]


IDEAS_SUBDIR = "ideas"
PUBLISHED_VIDEOS_FILE = "published_videos.json"
_TITLE_STOPWORDS: frozenset[str] = frozenset(
    {
        # filler verbs / connectors
        "como",
        "para",
        "cuando",
        "donde",
        "sobre",
        "entre",
        "desde",
        "todo",
        "todos",
        "todas",
        "esto",
        "esta",
        "estos",
        "estas",
        "este",
        "ese",
        "esa",
        "esos",
        "esas",
        "otro",
        "otra",
        "otros",
        "otras",
        "tanto",
        "tanta",
        "tantos",
        "tantas",
        # comparatives / common adverbs
        "menos",
        "mucho",
        "mucha",
        "muchos",
        "muchas",
        "poco",
        "poca",
        "pocos",
        "pocas",
        "muy",
        "mejor",
        "peor",
        "casi",
        "siempre",
        "nunca",
        "tambien",
        "ademas",
        "solo",
        "solamente",
        # generic time / age positioning the channel reuses on every title
        "despues",
        "antes",
        "ahora",
        "anos",
        "tiempo",
        "edad",
        # channel-positioning fragments (vida plena 45+)
        "vida",
        "plena",
        # other filler nouns that don't carry semantic meaning alone
        "manera",
        "forma",
        "modo",
        "tipo",
        "tipos",
        "veces",
        "vez",
        "parte",
        "partes",
        "lado",
        "lados",
        "caso",
        "casos",
        "cosa",
        "cosas",
        "ayuda",
        "ayudar",
        "puedes",
        "tener",
        "hacer",
        "hace",
    }
)
_NICHE_KW_MAP: dict[str, list[str]] = {
    "health_wellness": ["salud", "bienestar", "cuerpo", "mente", "vida"],
    "nutrition_45plus": ["nutrición", "alimentación", "dieta", "comer", "nutricion"],
    "exercise_low_impact": [
        "ejercicio",
        "caminar",
        "yoga",
        "movimiento",
        "actividad",
        "estiramiento",
    ],
    "sleep_quality": ["sueño", "dormir", "descanso", "insomnio", "sueno"],
    "mental_health": ["estrés", "ansiedad", "depresión", "mental", "emocional", "estres"],
    "hormonal_health": ["menopausia", "hormonas", "tiroides", "climaterio"],
    "cardiovascular": ["corazón", "presión", "colesterol", "circulación", "corazon"],
    "diabetes": ["diabetes", "glucosa", "azúcar", "insulina"],
    "weight_management": ["peso", "adelgazar", "grasa", "metabolismo", "obesidad"],
}
_CATEGORY_KW_MAP: dict[str, list[str]] = {
    "health_wellness": ["salud", "bienestar", "médico", "cuerpo", "medico"],
    "fitness": ["ejercicio", "fitness", "deporte", "gym"],
    "food": ["comida", "receta", "cocina", "alimento"],
    "beauty": ["belleza", "piel", "cabello", "antiedad"],
}
_REQUIRED_FIELDS = {"topic", "angle", "target_duration_sec", "key_points", "title_seed"}
DEFAULT_CHANNEL_KEYWORD_CONFIG = {
    "channel_name": "Vida Plena 45+: Salud y Bienestar",
    "target_language": "spanish",
    "target_audience": "people_45_plus",
    "audience_markers": [
        "45",
        "45+",
        "despues de los 45",
        "después de los 45",
        "mayores de 45",
        "a partir de los 45",
        "despues de los cuarenta",
        "después de los cuarenta",
    ],
    "core_topics": [
        "nutricion",
        "nutrición",
        "alimentacion",
        "alimentación",
        "comer mejor",
        "comer bien",
        "salud",
        "bienestar",
        "energia",
        "energía",
        "sueño",
        "dormir",
        "descanso",
        "habitos",
        "hábitos",
        "movimiento",
        "caminar",
        "estres",
        "estrés",
        "ansiedad",
        "peso",
        "metabolismo",
    ],
    "content_positioning": [
        "sin dietas extremas",
        "sin culpa",
        "sin caos",
        "simple",
        "practico",
        "práctico",
        "realista",
        "calma",
        "vida plena",
    ],
    "enable_serp_inspection": False,
    "serp_max_results": 10,
    "max_keywords_per_intent_cluster": 3,
    "target_locale": "Spain",
    "locale_language_code": "es-ES",
    "lexical_prefer": [
        "móvil",
        "ordenador",
        "por la tarde",
        "de madrugada",
        "personas de más de 45 años",
    ],
    "lexical_avoid": [
        "celular",
        "computadora",
        "LatAm",
        "adultos mayores",
        "tercera edad",
        "ancianos",
    ],
}
PORTUGUESE_MARKERS = [
    "depois",
    "voce",
    "você",
    "saude",
    "saúde",
    "bem-estar",
    "efeito sanfona",
    "comer bem",
    "sem culpa",
    "mais energia",
    "dieta maluca",
    "emagrecer",
    "sono",
    "cafe da manha",
    "café da manhã",
    "refeicao",
    "refeição",
    "almoco",
    "almoço",
    "jantar",
    "apos os 45",
    "após os 45",
    "aos 45",
]
SPANISH_MARKERS = [
    "despues",
    "después",
    "sin culpa",
    "salud",
    "bienestar",
    "energia",
    "energía",
    "sueno",
    "sueño",
    "dormir",
    "alimentacion",
    "alimentación",
    "nutricion",
    "nutrición",
    "comer mejor",
    "habitos",
    "hábitos",
]
ENGLISH_MARKERS = [
    "best camera settings",
    "weight loss",
    "sleep tips",
    "morning routine",
    "diet plan",
    "workout routine",
    "healthy aging",
]
FRENCH_MARKERS = [
    "apres 45 ans",
    "bien-etre",
    "mieux dormir",
    "perdre du poids",
    "manger mieux",
]
ITALIAN_MARKERS = [
    "dopo i 45",
    "dopo 45 anni",
    "dormire meglio",
    "mangiare meglio",
    "benessere dopo",
    "muoversi dopo",
]
_AGE_CHANNEL_MARKERS = ["45", "45+", "cuarenta"]
INTENT_KEYWORDS = [
    (
        "nutrition_after_45",
        ["comer", "alimentacion", "nutricion", "plato", "comida", "dieta", "proteina", "fibra"],
    ),
    ("energy_after_45", ["energia", "cansancio", "fatiga", "bajones", "ritmo"]),
    ("sleep_after_45", ["sueno", "dormir", "descanso", "insomnio", "noche"]),
    (
        "movement_after_45",
        ["movimiento", "caminar", "ejercicio", "fuerza", "musculo", "articulaciones"],
    ),
    (
        "emotional_wellbeing_after_45",
        ["estres", "ansiedad", "calma", "emocional", "mente", "motivacion"],
    ),
    (
        "weight_management_after_45",
        ["peso", "adelgazar", "bajar de peso", "metabolismo", "efecto rebote", "efecto yoyo"],
    ),
    ("general_health_after_45", ["salud", "bienestar", "habitos"]),
]
UNSAFE_CLAIMS = ["cura", "curar", "garantizado", "milagro", "elimina para siempre"]
GENERIC_KEYWORDS = {"salud", "bienestar", "nutricion", "dieta"}
HIGH_RISK_MEDICAL_TOPICS = [
    "diabetes",
    "hipertension",
    "hipertensión",
    "tiroides",
    "colesterol",
    "osteoporosis",
]
VALID_45PLUS_SENSITIVE_TOPICS = [
    "menopausia",
    "perimenopausia",
    "sofocos",
    "cambios hormonales",
]
MAX_PUBLISHED_TITLES_IN_IDEA_PROMPT = 30
