"""SEO/title artifact for infographic Shorts, reusing the shipped Shorts title rules.

An infographic Short has no independent thumbnail: its first spoken line and first
frame repeat the scroll-stopper idea from ``poster_plan["hook_line"]``. So the SEO
title is generated by the same ``build_short_seo`` path as narrated Shorts (the 4
scroll-stopper formulas, <=40 chars, age-framed, hook-aligned), seeded with the
poster plan's hook_line as the hook.
"""
from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any

from video_agent.shorts.infographic.voiceover import build_narration_text
from video_agent.shorts.short_seo_builder import build_short_seo


def build_infographic_seo(
    long_job_dir: Path,
    short_id: str,
    plan: dict[str, Any],
    channel_config: dict,
    llm_fn: Callable[..., str],
    *,
    long_video_url: str = "",
) -> dict[str, Any]:
    """Build + persist ``<job>/shorts/<short_id>/json/short_seo.json`` for an infographic Short.

    ``build_short_seo`` writes the artifact itself (to ``short_json_dir``) and
    enforces the title contract, so this is a thin adapter that maps the poster
    plan onto the Short SEO inputs (hook = the poster's ``hook_line``).
    """
    short_plan = {
        "short_id": short_id,
        "format": "infographic",
        "title": plan.get("title") or "",
        "viewer_pain": plan.get("hook_line") or plan.get("title") or "",
        "practical_payoff": plan.get("cta") or "",
    }
    short_script = {
        "hook": plan.get("hook_line") or plan.get("title") or "",
        "narration": build_narration_text(plan),
        "cta": plan.get("cta") or "",
    }
    return build_short_seo(
        Path(long_job_dir),
        short_id,
        short_plan,
        short_script,
        channel_config,
        llm_fn,
        long_video_url=long_video_url,
    )
